import 'package:equatable/equatable.dart';

/// Pure domain entity for a patient.
///
/// No Drift dependency — safe to import in any layer.
/// Generated by [UuidGenerator] before persistence; never use auto-increment.
class PatientEntity extends Equatable {
  const PatientEntity({
    required this.id,
    required this.name,
    required this.dateOfBirth,
    required this.gender,
    this.occupation,
    this.maritalStatus,
    this.numberOfChildren,
    this.createdBy = 'local_doctor',
    required this.createdAt,
  });

  // ─── Fields ─────────────────────────────────────────────────────────────────

  /// UUID v4 string. Must be set before calling [PatientRepository.createPatient].
  final String id;
  final String name;
  final DateTime dateOfBirth;

  /// 'Male', 'Female', or 'Other'.
  final String gender;
  final String? occupation;
  final String? maritalStatus;
  final int? numberOfChildren;
  final String createdBy;
  final DateTime createdAt;

  // ─── Factory ─────────────────────────────────────────────────────────────────

  factory PatientEntity.create({
    required String id,
    required String name,
    required DateTime dateOfBirth,
    required String gender,
    String? occupation,
    String? maritalStatus,
    int? numberOfChildren,
    String createdBy = 'local_doctor',
  }) {
    return PatientEntity(
      id: id,
      name: name,
      dateOfBirth: dateOfBirth,
      gender: gender,
      occupation: occupation,
      maritalStatus: maritalStatus,
      numberOfChildren: numberOfChildren,
      createdBy: createdBy,
      createdAt: DateTime.now(),
    );
  }

  // ─── CopyWith ────────────────────────────────────────────────────────────────

  PatientEntity copyWith({
    String? name,
    DateTime? dateOfBirth,
    String? gender,
    String? occupation,
    String? maritalStatus,
    int? numberOfChildren,
  }) {
    return PatientEntity(
      id: id,
      name: name ?? this.name,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      gender: gender ?? this.gender,
      occupation: occupation ?? this.occupation,
      maritalStatus: maritalStatus ?? this.maritalStatus,
      numberOfChildren: numberOfChildren ?? this.numberOfChildren,
      createdBy: createdBy,
      createdAt: createdAt,
    );
  }

  @override
  List<Object?> get props => [
        id,
        name,
        dateOfBirth,
        gender,
        occupation,
        maritalStatus,
        numberOfChildren,
        createdBy,
        createdAt,
      ];
}
